.PHONY: clean

CPPFLAGS := -std=c++0x

# Default target
all: use_student use_stack stackp1_test twod pairs tempmemb tempparm

use_student: student.cpp
use_stack: use_stack.cpp
stackp1_test: stackp1_test.cpp
twod: twod.cpp
pairs: pairs.cpp
tempmemb: tempmemb.cpp
tempparm: tempparm.cpp

clean:
	-rm use_student use_stack stackp1_test twod pairs tempmemb tempparm