.PHONY: clean

CPPFLAGS := -std=c++0x

BINARIES := use_student use_stack stackp1_test twod pairs tempmemb tempparm friend2temp temp2temp manyfriend

# Default target
all: $(BINARIES)

use_student: student.cpp
use_stack: use_stack.cpp
stackp1_test: stackp1_test.cpp
twod: twod.cpp
pairs: pairs.cpp
tempmemb: tempmemb.cpp
tempparm: tempparm.cpp
friend2temp: friend2temp.cpp
temp2temp: temp2temp.cpp
manyfriend: manyfriend.cpp

clean:
	-rm $(BINARIES)