.PHONY: all clean

CPPFLAGS := -std=c++0x

BINARIES := use_student use_stack stackp1_test twod pairs tempmemb tempparm friend2temp temp2temp manyfriend

all: $(BINARIES)

use_student: use_student.cpp student.cpp student.hpp

clean:
	-rm $(BINARIES) *.o *~
