.PHONY: all clean

BINARIES := ex1 ex2 ex3 ex4 ex5

all: $(BINARIES)

ex1: ex1.cpp cow.cpp cow.hpp
ex2: ex2.cpp string2.cpp string2.hpp
ex3: ex3.cpp stock02.cpp stock02.hpp
ex4: ex4.cpp stack.cpp stack.hpp
ex5: ex5.cpp queue.cpp queue.hpp

clean:
	-rm $(BINARIES) *~ *.o