.PHONY: all clean

CXXFLAGS := -std=c++0x

BINARIES := addpointers address arraynew arrayone arr_struct assign_struct choices delete init_ptr instr1 instr2 instr3 mixtypes newstruct numstr pointer ptrstr strings strtype1 strtype2 strtype3 strtype4 structur use_new utf8

all: $(BINARIES)

clean:
	-rm $(BINARIES) *~ *.o