.PHONY: all clean

CXXFLAGS := -std=c++0x

BINARIES := write defaults manip width fill precise showpt setf \
            setf2 iomanip check_it cinexcp get_fun peeker truncate \
            fileio count append binary random strout strin

all: $(BINARIES)

clean:
	-rm $(BINARIES) *~
