.PHONY: all clean

CXXFLAGS := -std=c++0x

BINARIES := choices cubes filefunc funtemp left leftover rrefs secref strc_ref strquote swaps tempover twoswap twotemps

all: $(BINARIES)

clean:
	-rm $(BINARIES) *~ *.o